version: '3.8'
services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=00000000
    volumes:
      # - ./dbdata:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
        - 27017:27017
  cache:
    image: redis
    container_name: cache
    ports:
        - 6379:6379
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    container_name: server
    restart: always
    environment:
      - PUBLISH=publish
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=00000000
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
      - MONGO_DB=url_db
      - REDIS_URL=redis://cache
    ports:
        - "3000:3000"