version: '3.8'
services:
  db:
    image: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./dbdata:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
        - 27017:27017
  cache:
    image: redis
    container_name: cache
    ports:
        - 6379:6379
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    container_name: server
    restart: always
    env_file: .env
    environment:
      - PUBLISH=publish
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - REDIS_URL=$REDIS_URL
    ports:
        - "3000:3000"